# Generated by Django 5.0 on 2024-03-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartcrsapp', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
