# Generated by Django 5.0 on 2024-03-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartcrsapp', '0003_remove_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='datas',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='datas',
            old_name='Name',
            new_name='name',
        ),
    ]
