# Generated by Django 5.0 on 2024-04-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartcrsapp', '0004_rename_mail_datas_mail_rename_message_datas_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
